### ISSUE TITLE
UnhandledPromiseRejectionWarning when migrating by label

### ISSUE THREAD

**Issue by EliiseS** [buildo/gh-issue-mover#8]
While migrate by label an `UnhandledPromiseRejectionWarning` occured. The migration was still successful despite the error.

## Error
```sh
🖖  Greetings, hooman!

🚚  Ready to migrate issues from microsoft/terraform-provider-azuredevops to terraform-providers/terraform-provider-azuredevops?

? How do you want to migrate the issues? by label
? Cool, which labels? (separate multiple labels with commas. They will go in AND) new feature, question
Sorry, no issues found matching labels new feature,question
? Do you want to try again? Yes
? How do you want to migrate the issues? by label
? Cool, which labels? (separate multiple labels with commas. They will go in AND) "new feature"
Sorry, no issues found matching labels "new feature"
? Do you want to try again? Yes
? How do you want to migrate the issues? by label
? Cool, which labels? (separate multiple labels with commas. They will go in AND) question
? You're about to migrate 2 issues matching the labels question . Are you sure? Yes
(node:50752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at Function.all (<anonymous>)
    at _callee3$ (/usr/lib/node_modules/gh-issue-mover/lib/index.js:176:28)
    at tryCatch (/usr/lib/node_modules/gh-issue-mover/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/lib/node_modules/gh-issue-mover/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/lib/node_modules/gh-issue-mover/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/lib/node_modules/gh-issue-mover/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/lib/node_modules/gh-issue-mover/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
(node:50752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:50752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 🍭  Successfully migrated issue from microsoft/terraform-provider-azuredevops#378 to terraform-providers/terraform-provider-azuredevops#28 


 🍭  Successfully migrated issue from microsoft/terraform-provider-azuredevops#379 to terraform-providers/terraform-provider-azuredevops#27 
```

**Comment by acourtiol** [comment]
Had the same issue (if I can call it an issue as everything was still successful)
